### ISSUE TITLE
RTBH 'next-hop' field condition

### ISSUE THREAD

**Issue by josephKhoury95** [dataplane/rtbh-collector#4]
Hello,

In your code you used this IP address " 80.81.193.66" to compare it with  `elem.fields['next-hop']`.
I am assuming this particular IP address is the one used to diverge the traffic to. Please correct me if I am wrong on this.

Now, If there is no specific IP address(es) that I am aware of that are being used for black holing, what would I place instead of this condition: `if elem.fields['next-hop'] == "80.81.193.66"`?

Any help on this is much appreciated.
Thank you.

**Comment by jtkristoff** [comment]
This repo is years old and was a prototype when it was created. It is no longer maintained. I believe that address was an example and would have to be maintained or altered to reflect the RTBH method in use.
